FROM node:18

WORKDIR /app

# Instala dependências do sistema para o Playwright
RUN apt-get update && npx playwright install-deps

COPY package*.json ./
RUN npm install
RUN npx playwright install
COPY . .

CMD ["npm", "start"]
